//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnquiryManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnquiryModelContainer : DbContext
    {
        public EnquiryModelContainer()
            : base("name=EnquiryModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<CustomerProfile> CustomerProfiles { get; set; }
        public virtual DbSet<EnquiryType> EnquiryTypes { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<SalesTeam> SalesTeams { get; set; }
        public virtual DbSet<Opportunity> Opportunities { get; set; }
        public virtual DbSet<EnquiryRisk> EnquiryRisks { get; set; }
        public virtual DbSet<EnquiryStage> EnquiryStages { get; set; }
        public virtual DbSet<EnquiryStatu> EnquiryStatus { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RoleType> RoleTypes { get; set; }
    }
}
