//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnquiryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string FirmName { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string EnquiryDate { get; set; }
        public string Comments { get; set; }
        public string CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int EnquiryTypeId { get; set; }
        public int CustomerProfileId { get; set; }
        public int SalesTeamId { get; set; }
        public int EventId { get; set; }
        public int ApplicationId { get; set; }
        public int UserId { get; set; }
        public int AdvertisementId { get; set; }
        public IsUrgent IsUrgent { get; set; }
        public IsQualify IsQualify { get; set; }
        public IsDisQualify IsDisQualify { get; set; }
        public IsDeactivate IsDeactivate { get; set; }
    
        public virtual Opportunity Opportunity { get; set; }
        public virtual EnquiryType EnquiryType { get; set; }
        public virtual CustomerProfile CustomerProfile { get; set; }
        public virtual SalesTeam SalesTeam { get; set; }
        public virtual Event Event { get; set; }
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
        public virtual Advertisement Advertisement { get; set; }
    }
}
